#jms_security_extra:
#    secure_all_services: false
#    expressions: true

security:
  encoders:
    FOS\UserBundle\Model\UserInterface: sha512

  acl:
    connection: default

  role_hierarchy:
    ROLE_EDITOR: ROLE_USER
    ROLE_ADMIN: ROLE_EDITOR
    ROLE_SUPER_ADMIN: ROLE_ADMIN
    ROLE_ROOT: ROLE_SUPER_ADMIN, ROLE_USER


  providers:
    fos_userbundle_user:
      id: fos_user.user_provider.username_email

  firewalls:
    main:
      pattern: ^/
#      oauth:
#        login_path: /logowanie-rejestracja.html
#        failure_path: /logowanie-rejestracja.html
#        resource_owners:
#          google: /login/google
#          facebook: /login/facebook
#          linkedin: /login/linkedin
#        oauth_user_provider:
#          service: hwi_oauth.user.provider.fosub_bridge
      form_login:
        provider: fos_userbundle_user
        csrf_provider: form.csrf_provider
        login_path: /login
        default_target_path: /
      logout:       true
      anonymous:    true

  access_control:
    - { path: \.((css)|(js))$, role: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/admin, role: ROLE_ADMIN }
    - { path: ^/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/, role: IS_AUTHENTICATED_ANONYMOUSLY }


fos_user:
    db_driver: orm
    firewall_name: main
    user_class: Hexmedia\UserBundle\Entity\User
    registration:
        form:
            type: hexmedia_user_registration
        confirmation:
            enabled: false
    from_email:
        address: %mail_from%
        sender_name: %mail_from_name%
    service:
        mailer: fos_user.mailer.twig_swift
